# VIEW
VIEW_SETTINGS_TITLE = 'Settings'
VIEW_BUTTON_SAVE = 'Save'
VIEW_BUTTON_SAVE_KEY = '-saveSettings-'
VIEW_TEXT_LOG = "Log"
VIEW_TEXT_CURRENT_STATE = "Current state"
VIEW_BUTTON_CLEAR_LOG = "Clear Log"
VIEW_BUTTON_CLEAR_LOG_KEY = "-clearLog-"
VIEW_BUTTON_GO = 'Run'
VIEW_BUTTON_GO_KEY = '-goButton-'
VIEW_BUTTON_CURSOR_VALUE = 'Cursor Value'
VIEW_BUTTON_CURSOR_VALUE_KEY = '-cursorValueButton-'
VIEW_BUTTON_PAUSE = 'Pause Bot'
VIEW_BUTTON_PAUSE_KEY = '-pause-'
VIEW_BUTTON_VIEW_PAUSE = 'Pause Capture'
VIEW_BUTTON_VIEW_PAUSE_KEY = '-viewPause-'
VIEW_BUTTON_EXIT = 'Exit'
VIEW_BUTTON_EXIT_KEY = '-exit-'
VIEW_LOG_OUTPUT = '-logger-'
VIEW_LOG_CURRENT_STATE = '-clearLog-'
VIEW_CATCHED_FISHES_LABEL = "Fishes: "
VIEW_CATCHED_FISHES_KEY = "-catchedFishes-"
VIEW_CATCHED_ITEMS_LABEL = "Items: "
VIEW_CATCHED_ITEMS_KEY = "-catchedItems-"

VIEW_TEXT_CURSOR_VALUE_LABEL = 'Cursor Value'
VIEW_TEXT_CURSOR_VALUE_KEY = '-cursorValue-'
VIEW_TEXT_COLOR_PREVIEW_KEY = '-colorPreview-'
VIEW_TEXT_CURSOR_VALUE_IMAGE_KEY = '-cursorValueImage-'

# SETTINGS ROD
VIEW_SETTINGS_ROD_TITLE = 'Rod'

VIEW_SETTINGS_ROD_RED_LABEL = 'R'
VIEW_SETTINGS_ROD_RED = '-rodRed-'

VIEW_SETTINGS_ROD_GREEN_LABEL = 'G'
VIEW_SETTINGS_ROD_GREEN = '-rodGreen-'

VIEW_SETTINGS_ROD_BLUE_LABEL = 'B'
VIEW_SETTINGS_ROD_BLUE = '-rodBlue-'

VIEW_SETTINGS_ROD_PERCENTAGE_LABEL = '%'
VIEW_SETTINGS_ROD_PERCENTAGE = '-rodPercentage-'

VIEW_SETTINGS_ROD_START_X_LABEL = 'Start X'
VIEW_SETTINGS_ROD_START_X = '-rodStartX-'

VIEW_SETTINGS_ROD_START_Y_LABEL = 'Start Y'
VIEW_SETTINGS_ROD_START_Y = '-rodStartY-'

VIEW_SETTINGS_ROD_END_X_LABEL = 'End X'
VIEW_SETTINGS_ROD_END_X = '-rodEndX-'

VIEW_SETTINGS_ROD_END_Y_LABEL = 'End Y'
VIEW_SETTINGS_ROD_END_Y = '-rodEndY-'

VIEW_SETTINGS_ROD_COLOR = '-rodColorPreview-'
VIEW_SETTINGS_ROD_IMAGE = '-rodImage-'

# BAIT
VIEW_SETTINGS_BAIT_TITLE = 'Bait'

VIEW_SETTINGS_BAIT_START_X_LABEL = 'Start X'
VIEW_SETTINGS_BAIT_START_X = '-baitStartX-'

VIEW_SETTINGS_BAIT_START_Y_LABEL = 'Start Y'
VIEW_SETTINGS_BAIT_START_Y = '-baitStartY-'

VIEW_SETTINGS_BAIT_END_X_LABEL = 'End X'
VIEW_SETTINGS_BAIT_END_X = '-baitEndX-'

VIEW_SETTINGS_BAIT_END_Y_LABEL = 'End Y'
VIEW_SETTINGS_BAIT_END_Y = '-baitEndY-'

VIEW_SETTINGS_BAIT_RED_LABEL = 'R'
VIEW_SETTINGS_BAIT_RED = '-baitRed-'

VIEW_SETTINGS_BAIT_GREEN_LABEL = 'G'
VIEW_SETTINGS_BAIT_GREEN = '-baitGreen-'

VIEW_SETTINGS_BAIT_BLUE_LABEL = 'B'
VIEW_SETTINGS_BAIT_BLUE = '-baitBlue-'

VIEW_SETTINGS_BAIT_PERCENTAGE_LABEL = '%'
VIEW_SETTINGS_BAIT_PERCENTAGE = '-baitPercentage-'

VIEW_SETTINGS_BAIT_COLOR = '-baitColorPreview-'
VIEW_SETTINGS_BAIT_IMAGE = '-baitImage-'

# CATCHING_BOX
VIEW_SETTINGS_CATCHING_BOX_TITLE = 'Catch Box'

VIEW_SETTINGS_CATCHING_BOX_START_X_LABEL = 'Start X'
VIEW_SETTINGS_CATCHING_BOX_START_X = '-catchingBoxStartX-'
VIEW_SETTINGS_CATCHING_BOX_START_Y_LABEL = 'Start Y'
VIEW_SETTINGS_CATCHING_BOX_START_Y = '-catchingBoxStartY-'
VIEW_SETTINGS_CATCHING_BOX_END_X_LABEL = 'End X'
VIEW_SETTINGS_CATCHING_BOX_END_X = '-catchingBoxEndX-'
VIEW_SETTINGS_CATCHING_BOX_END_Y_LABEL = 'End Y'
VIEW_SETTINGS_CATCHING_BOX_END_Y = '-catchingBoxEndY-'

VIEW_SETTINGS_CATCHING_BOX_RED_LABEL = 'R'
VIEW_SETTINGS_CATCHING_BOX_RED = '-catchingBoxRed-'
VIEW_SETTINGS_CATCHING_BOX_GREEN_LABEL = 'G'
VIEW_SETTINGS_CATCHING_BOX_GREEN = '-catchingBoxGreen-'
VIEW_SETTINGS_CATCHING_BOX_BLUE_LABEL = 'B'
VIEW_SETTINGS_CATCHING_BOX_BLUE = '-catchingBoxBlue-'
VIEW_SETTINGS_CATCHING_BOX_PERCENTAGE_LABEL = '%'
VIEW_SETTINGS_CATCHING_BOX_PERCENTAGE = '-catchingBoxPercentage-'

VIEW_SETTINGS_CATCHING_BOX_COLOR = '-catchingBoxColorPreview-'
VIEW_SETTINGS_CATCHING_BOX_IMAGE = '-catchingBoxImage-'

# FISH_FIGHTING
VIEW_SETTINGS_FISH_FIGHTING_TITLE = 'Fish Fighting'

VIEW_SETTINGS_FISH_FIGHTING_START_X_LABEL = 'Start X'
VIEW_SETTINGS_FISH_FIGHTING_START_X = '-fishFightingStartX-'
VIEW_SETTINGS_FISH_FIGHTING_START_Y_LABEL = 'Start Y'
VIEW_SETTINGS_FISH_FIGHTING_START_Y = '-fishFightingStartY-'
VIEW_SETTINGS_FISH_FIGHTING_END_X_LABEL = 'End X'
VIEW_SETTINGS_FISH_FIGHTING_END_X = '-fishFightingEndX-'
VIEW_SETTINGS_FISH_FIGHTING_END_Y_LABEL = 'End Y'
VIEW_SETTINGS_FISH_FIGHTING_END_Y = '-fishFightingEndY-'

VIEW_SETTINGS_FISH_FIGHTING_RED_LABEL = 'R'
VIEW_SETTINGS_FISH_FIGHTING_RED = '-fishFightingRed-'
VIEW_SETTINGS_FISH_FIGHTING_GREEN_LABEL = 'G'
VIEW_SETTINGS_FISH_FIGHTING_GREEN = '-fishFightingGreen-'
VIEW_SETTINGS_FISH_FIGHTING_BLUE_LABEL = 'B'
VIEW_SETTINGS_FISH_FIGHTING_BLUE = '-fishFightingBlue-'
VIEW_SETTINGS_FISH_FIGHTING_PERCENTAGE_LABEL = '%'
VIEW_SETTINGS_FISH_FIGHTING_PERCENTAGE = '-fishFightingPercentage-'

VIEW_SETTINGS_FISH_FIGHTING_COLOR = '-fishFightingColorPreview-'
VIEW_SETTINGS_FISH_FIGHTING_IMAGE = '-fishFightingBarImage-'

# CAST ROD CLICK POSITION
VIEW_SETTINGS_CAST_ROD_CLICK_POSITION_TITLE = 'Click Position'

VIEW_SETTINGS_CAST_ROD_CLICK_POSITION_X_LABEL = 'X'
VIEW_SETTINGS_CAST_ROD_CLICK_POSITION_X = '-castClickPositionStartX-'
VIEW_SETTINGS_CAST_ROD_CLICK_POSITION_Y_LABEL = 'Y'
VIEW_SETTINGS_CAST_ROD_CLICK_POSITION_Y = '-castClickPositionStartY-'

# STATES
STATE_IDLE = "Idle"
STATE_CASTING_ROD = "Casting Rod"
STATE_FISHING = "Fishing"
STATE_BITE = "Bite"
STATE_CATCHING = "Catching"
STATE_FISH_FIGHTING = "Fish Fighting"
STATE_PULL_IN = "Pull In"
STATE_RELEASE_LINE = "Release Line"

# TRANSITION
TRANSITION_IDLE = 'toIdle'
TRANSITION_CASTING_ROD = 'toCastingRod'
TRANSITION_FISHING = 'toFishing'
TRANSITION_BITE = 'toBite'
TRANSITION_CATCHING = 'toCatching'
TRANSITION_FISH_FIGHTING = 'toFishFighting'
TRANSITION_PULL_IN = 'toPullIn'
TRANSITION_RELEASE_LINE = 'toReleaseLine'

# FILES
SETTINGS_FILE_NAME = 'settings.json'
